import { Analytics } from "@vercel/analytics/next"
import { Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const tanHeadline = localFont({
  src: [
    {
      path: "./fonts/TANHEADLINE-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-tan-headline",
});

const circular = localFont({
  src: [
    {
      path: "./fonts/circular-medium.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-circular",
});

const robotoSans = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "RidingSafaris Web Map",
  description: "Generated by Black Saddle",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${robotoSans.variable} ${tanHeadline.variable} ${circular.variable}`}>
      <body className="antialiased font-sans">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
